---@meta Opts.StatusBar
error "cannot require a meta file!"

-- luacheck: push ignore 631 (line is too long)

---@alias Opts.StatusBar.Module.ConditionChecker fun(window: Window, pane: Pane): boolean
---@alias Opts.StatusBar.Module.ValueProvider     fun(window: Window, pane: Pane): string

---Status bar configuration options.
---Covers layout, refresh cadence, and module styling.
---
---@class Opts.StatusBar
---@field public enabled?  boolean                                Enable the status bar.
---@field public position? "top"|"bottom"                         Screen position of status bar.
---@field public fancy?    boolean                                Use the fancy tab bar.
---@field public flexible? boolean                                Allow the status bar to shrink when space is tight.
---@field public padding?  number|{ left: number, right: number } Component padding applied after text and icon are combined.
---@field public style?    Opts.StatusBar.Module.Styler           Component style applied to both icon and text.
---@field public layout?   Opts.StatusBar.Layout                  Structural arrangement of status bar components.
---@field public modules?  Opts.StatusBar.Modules                 Collection of module-specific configurations.
---
---
---Layout configuration for status bar sides.
---@class Opts.StatusBar.Layout
---@field public left?  Opts.StatusBar.Layout.Item[] List of module names for left-aligned section.
---@field public right? Opts.StatusBar.Layout.Item[] List of module names for right-aligned section.
---
---
---@alias Opts.StatusBar.Layout.Item
---| (string | string[])
---
---
---@alias Opts.StatusBar.Modules
---| table<string, (Opts.StatusBar.Module|Opts.StatusBar.Module.Creator)>
---
---
---@alias Opts.StatusBar.Module.Creator
---| fun(window: Window, pane: Pane, theme, config): Opts.StatusBar.Module
---
---
---Configuration for one status bar module.
---@class Opts.StatusBar.Module
---@field public enabled?  boolean                                Enable this module.
---@field public cond?     boolean|Opts.StatusBar.Module.ConditionChecker   Whether the module is visible.
---@field public icon?     Opts.StatusBar.Module.Icon             Icon displayed next to the text.
---@field public text?     Opts.StatusBar.Module.Text             Text displayed next to the icon.
---@field public sep?      Opts.StatusBar.Module.Sep              Separator displayed with the module.
---@field public style?    Opts.StatusBar.Module.Styler           Module style.
---@field public layout?   Opts.StatusBar.Module.Layout           Static or dynamic layout of the module.
---@field public can_hide? boolean                                Whether the module may be hidden.
---@field public padding?  number|{ left: number, right: number } Component padding.
---
---
---@class Opts.StatusBar.Module.Component
---@field public enabled? boolean                                    Whether the component is enabled.
---@field public value?   string|Opts.StatusBar.Module.ValueProvider       Component string value to display.
---@field public padding? number|{ left: number, right: number }     Component padding.
---@field public style?   Opts.StatusBar.Module.Styler               Component style.
---
---@class Opts.StatusBar.Module.Icon: Opts.StatusBar.Module.Component
---@field public position? "left"|"right"                         Icon position relative to the text.
---
---
---@class Opts.StatusBar.Module.Text: Opts.StatusBar.Module.Component
---
---
---@class Opts.StatusBar.Module.Sep : Opts.StatusBar.Module.Component
---@field public invert_bg_fg? boolean                          Invert the global background and foreground for separators.
---@field public value?        Opts.StatusBar.Module.Sep.Value
---
---
---@alias Opts.StatusBar.Module.Layout
---| string
---| table
---| Ribbon
---| fun(ctx: Opts.StatusBar.Module.LayoutContext): string|table|Ribbon
---
---@alias Opts.StatusBar.Module.LayoutContext
---| { layout: Ribbon.Api, theme: table, warp: Warp.Api, window: Window, pane: Pane }
---
---@alias Opts.StatusBar.Module.Styler
---| { bg?: string, fg?: string, attributes?: string|string[] }
---| fun(theme: table, parent_style?: { bg?: string, fg?: string, attributes?: string|string[] }): { bg?: string, fg?: string, attributes?: string|string[] }
---
---@alias Opts.StatusBar.Module.Sep.Value
---| string
---| { left: string, right: string }
---| (fun(window: Window, pane: Pane): string|{ left: string, right: string })

-- luacheck: pop
